This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./mabib0573.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file mabib0573.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file mabib0573.acr....done (6 lines written, 0 warnings).
Output written in mabib0573.acr.
Transcript written in mabib0573.alg.
